development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
<<<<<<< HEAD
  channel_prefix: analytic_counter_production
=======
  channel_prefix: talent_fore_production
>>>>>>> 967eb6bf2ecfd5b1ec932c74e24ca2d87334443d
